import {ProductDto} from "./rest-client";

export const products : ProductDto[] = [
    {
        id: 0,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 1,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 2,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 3,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 4,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 5,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 6,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 7,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 8,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 9,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 10,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 11,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 12,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 13,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 14,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 15,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 16,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    },
    {
        id: 17,
        price: 0,
        count: 0,
        instant: 0,
        productionTime: 0,
        title: "string",
        description: "string",
    }
]